modLoader="javafml"
loaderVersion="[36,)"
license="LGPL"
issueTrackerURL="https://github.com/Cazsius/ExperienceOre/issues"
[[mods]] 
modId="experienceore" 
version="${file.jarVersion}" 
displayName="ExperienceOre"
description='''
A simple mod that adds ore that drops experience!
'''
[[dependencies.experienceore]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.experienceore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
